### ISSUE TITLE
Doesn't work for me ?

### ISSUE THREAD

**Issue by YohanRodriguezMDM** [vdohney/keepass-password-dumper#1]
Hi there, It doesn't work for me, here is the output :

```
Password candidates (character positions):
1.:     Unknown
2.:     8,  , ', B, ), A, G, I, ], a, ^, F, 5, 9, ., &, C, (, S,
Combined: {UNKNOWN}{8,  , ', B, ), A, G, I, ], a, ^, F, 5, 9, ., &, C, (, S}
```

I used the dump from task manager.
KeePass 2.53.1 & .NET SDK 7.0

**Comment by vdohney** [comment]
Hello YohanRodriguezMDM, thanks for reaching out!

**Is it possible that you have copied the password into the textbox**, instead of typing it? That shouldn’t be impacted, although I saw some people reproducing it for that too ([video 1](https://www.linkedin.com/posts/or-hamra_httpslnkdindpqpzjb9-keepass-2x-before-activity-7064312298680500224-myxH), [video 2](https://www.linkedin.com/posts/leubincloud_keepass-changemasterpwd-activity-7064346677872087040--HCu))

Also, could you please provide more information, like the memory dump itself, OS etc. (of course **only if there’s nothing sensitive**). It’s hard to judge based on this alone.

Btw, what language are you using on your OS? Maybe this is related to encoding or something like that. I’ve tested it on Windows with English as a main language only.

**Comment by YohanRodriguezMDM** [comment]
I retried after stopping and restarting KeePass and it worked.
